name: Pioneer Desktop Factory
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
        steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Decode Certificate
        run: |
          echo "${{ secrets.P12_BASE64 }}" > cert.p12.base64
          certutil -decode cert.p12.base64 cert.p12

      - name: Install & Build
        run: |
          npm install
          npm install && npx electron-rebuild
          npm run build
        env:
          CSC_LINK: ${{ github.workspace }}\cert.p12
          CSC_KEY_PASSWORD: ${{ secrets.P12_PASSWORD }}

      - name: Upload Signed Pioneer
        uses: actions/upload-artifact@v4
        with:
          name: Pioneer-OS-Windows-Signed
          path: dist/*.exe
